### ISSUE TITLE
Храним данные по знаменитостям во внешней памяти

### ISSUE THREAD

**Issue by vbarhatov** [ibarhatov/HelloWorld#11]
Добавить загрузку данных по знаменитостям из файла.
Способы выбора файла:
1. по умолчанию загрузка происходит из файла "stars"
2. специальным входным параметром можно переопределить имя файла
Расширение имени файла остается на усмотрение разработчика

Предусмотреть возможность редактирования базы со знаменитостями

**Comment by ibarhatov** [comment]
Первый черновой вариант хранения базы знаменитостей во внешней памяти выполнен. Чтение и запись производится в файл и директорию, определенные разработчиком. c93724db6004bb05aff9bec219cea64a944fb3e7

**Comment by ibarhatov** [comment]
Реализован пункт 2: входным параметром пользователь может указать собственный файл с базой знаменитостей. f6222eed9a955a8aaf408a1bc7a560a1913eb679
