### ISSUE TITLE
Сделать учет пола при поиске похожестей

### ISSUE THREAD

**Issue by vbarhatov** [ibarhatov/HelloWorld#12]
Сейчас при поиске похожестей по знаменитостям не учитывается пол пользователя. И в случае

```
Пользователь - 170 / 60 / М
Знаменитость1 - 168 / 63 / Ж
Знаменитость2 - 173 / 63 / М
```

будет выбрана похожесть со Знаменитость2

Необходимо добавить учет пола при сравнении, но не исключать противоположный пол полностью

**Comment by ibarhatov** [comment]
Done. 399f7367a1aa4f5febcb77cf7b20d677a149a45f
