### ISSUE TITLE
Читать параметры с консоли

### ISSUE THREAD

**Issue by vbarhatov** [ibarhatov/HelloWorld#2]
Читать входные параметры типа 
-name:Petr -age:27 -sex:man .....
и для введенных параметров не задавать вопросов, а использовать указанные значения.

**Comment by vbarhatov** [comment]
Любой параметр может быть указан или не указан в консоли

**Comment by ibarhatov** [comment]
Kороч пока такая поеботина d7319e493706123cafcdc805f071c4d1231d9606

**Comment by ibarhatov** [comment]
Compliete 39c43f55686d26606c48962e9f8663f910456080
