### ISSUE TITLE
Вынести данные о пользователе в класс

### ISSUE THREAD

**Issue by vbarhatov** [ibarhatov/HelloWorld#3]
Создать класс, описывающий пользователя: имя, рост, вес, возраст

В классе проработать необходимые поля, методы, конструкторы

**Comment by ibarhatov** [comment]
Данные о пользователе вынесены в отдельный класс.
Ввод параметров с консоли перемещен в класс пользовательских данных.
fab94a600b241839386d310be3ff23af4362b3c7

**Comment by ibarhatov** [comment]
Какие еще необходимы методы?

**Comment by vbarhatov** [comment]
When will you have done that?

**Comment by ibarhatov** [comment]
Класс пользователя сформирован 1a6488397f1fc1cd9cb4a41478a52e6038039c8d
