### ISSUE TITLE
Работа с датами и календарем

### ISSUE THREAD

**Issue by vbarhatov** [ibarhatov/HelloWorld#4]
Добавить дату рождения 

Возраст высчитывать с учетом текущей даты

**Comment by vbarhatov** [comment]
- Зачем нужна дата рождений, если мы не знаем как рассчитывать вес с учетом возраста?
- Дата рождения нужна для того, чтобы ты научился работать с датами.

**Comment by ibarhatov** [comment]
Запилил 290172bbfb3f8371cee03bd61d5b94c3a3504159
