### ISSUE TITLE
Корректное чтение параметров с командной строки

### ISSUE THREAD

**Issue by vbarhatov** [ibarhatov/HelloWorld#6]
Программа пропускает входные параметры в формате:

-name:vasya
-name-vasya
:name:vasya

Корректным форматом является только первый.

**Comment by ibarhatov** [comment]
Но она же его читает. Никто не говорил о том, чего она делать не должна

**Comment by vbarhatov** [comment]
Как быть с  `-name:vasya-pupkin` ?

**Comment by ibarhatov** [comment]
Все ок, имя она прочитает

**Comment by ibarhatov** [comment]
Добавлена требуемая проверка формата входных параметров 71611c07545d5b6a39ffaa0bfc2d974654d500b4
