### ISSUE TITLE
Добавить проверку на ошибки

### ISSUE THREAD

**Issue by vbarhatov** [ibarhatov/HelloWorld#7]
Входные параметры и данные с консоли не проверяются на ошибки.
В связи с этим допустимы ситуации, когда 
- любое значение отличное от "man" засчитывается как женский пол
- возраст, вес могут быть не числом 

Нужно добавить проверку на входные параметры

**Comment by ibarhatov** [comment]
Добавлена проверка входных параметров на предмет пола; 71611c07545d5b6a39ffaa0bfc2d974654d500b4

**Comment by ibarhatov** [comment]
Добавлена проверка на входные параметры роста и веса. ad49c3f71b9b58f8e756da7a05db39d19c886976
