### ISSUE TITLE
Сделать пол через enum

### ISSUE THREAD

**Issue by vbarhatov** [ibarhatov/HelloWorld#8]
Выполнить после https://github.com/ibarhatov/HelloWorld/issues/3

**Comment by ibarhatov** [comment]
Перевести - перевел. Где каша? a4f877b97aacbda705d39c906ca090d49672e15a

**Comment by vbarhatov** [comment]
Прокомментировал твой коммит, посмотри

**Comment by ibarhatov** [comment]
Выполнено 905f72f31de4315bec76677abfefc0dc7ad5b463
