### ISSUE TITLE
Сделать сравнение со звездами

### ISSUE THREAD

**Issue by vbarhatov** [ibarhatov/HelloWorld#9]
Добавить в рекомендации сравнение с известными личностями вида:

_Вы похожи на Чак Нориса, совпадение 83%_

Для сравнения использовать некоторую базу знаменитостей (около 10 человек) с различными характеристиками и подбирать наиболее подходящего по введенным данным.

**Comment by ibarhatov** [comment]
Первая версия готова. dbe431fd1c9db54b2f69670cf98604a466b2009a
Следующим шагом расширю базу знаменитостей и сделаю вывод наиболее подходящего.

**Comment by ibarhatov** [comment]
База расширена, сделан подбор наиболее подходящей персоны. dfd2b2440868edcc949ff278eebd4577b959496b
